name: tests

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:

  debug-build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.7", "6.2", "latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v2.4.0
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v7
      - name: Swift Version
        run: swift --version
      - name: Debug Build
        run: swift build -v -c debug
      - name: Debug Test
        run: swift test -v -c debug --enable-test-discovery